# Generated by Django 5.0.2 on 2024-03-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Detect", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionimage",
            name="reported",
            field=models.BooleanField(default=False),
        ),
    ]
