# Generated by Django 5.0.2 on 2024-03-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Detect", "0002_predictionimage_reported"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionimage",
            name="reported_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
